name: Matrix Build

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                node-version: [22, 23]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: |
               echo "Building on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}"
               npm run build